### ISSUE TITLE
Support for recurring events

### ISSUE THREAD

**Issue by gwww** [b4tman/sync_ics2gcal#87]
Nice looking code!

I didn't see support for recurring events (RRULE, EXDATE, etc). Am I reading this correctly? On the surface, to me, it seems easy to add. Wondering if you just didn't need it or there's some reason its not supported.

Thanks!

**Comment by b4tman** [comment]
Hi, @gwww! Thank you!

Yes recurring events not supported.
I'm just not using it, and don't know how to compare and sync such type of events.

If you have an idea i will be appreciated your help!

**Comment by gwww** [comment]
So I just playing right now. I may diverge from what you want from the code, so I've forked and will make changes I want. I have no idea if they will work. When/if I get done, I will share a PR back to you with no expectations that you will take it. But you'll be able to see what I did.

**Comment by gwww** [comment]
I've been playing a bit and found another solution that suits even better. It runs as a Google App Script and handles recurring events. The nice thing is I don't have to host the code on one of my own servers. I'm still playing with it but works well so far. https://github.com/derekantrican/GAS-ICS-Sync
